### PR TITLE
Switch hook call syntax to avoid false CPS warnings

### LINKED ISSUE #11: CPS Wrapping issues showing up in hook calls
`expected to call java.util.LinkedHashMap.preSetUpHook but wound up catching org.jenkinsci.plugins.workflow.cps.CpsClosure2.call;`

[Direct invocation of closures stored in object fields or maps](https://wiki.jenkins.io/display/JENKINS/Pipeline+CPS+method+mismatches#PipelineCPSmethodmismatches-Directinvocationofclosuresstoredinobjectfieldsormaps) appears to be the most likely explanation, since I took care (or, at least tried) to make sure everything going on in here was CPS-wrapped so that users can execute any arbitrary (but sandboxed) build steps in any hook, and that section heading exactly describes how the hooks are written to work.

There is a workaround mentioned in the linked doc, which is to change this:
```groovy
    def preSetUpHook() {
        job.echo('Running preSetUpHook')
        config.preSetUpHook(config)
    }
```

to this (call with `.call`):
```groovy
    def preSetUpHook() {
        job.echo('Running preSetUpHook')
        config.preSetUpHook.call(config)
    }
```

### PR DESCRIPTION
**Pull request by tehsmyers**
fixes #11

### CODE REVIEW

**Review by robled — APPROVED** [review]

**Comment by greg-hellings** [comment]
I mean, it looks good. But why is the test failing? Is that related to this, or is that related to something else?

**Comment by tehsmyers** [comment]
I put this in our little private team chat, but I probably should've put it here: All jenkins builds are currently failing because of [this psutil bug](https://github.com/giampaolo/psutil/issues/1615). I'm waiting to see how that's handled before suggesting workarounds.

**Comment by tehsmyers** [comment]
And now github refs have that issue pointing at this issue, which on the face of it appears entirely unrelated. Hooray!

That bug references a pip enhancement, so I'll just mention that I haven't done any more digging beyond the psutil bug report that matches what I'm seeing in our build logs. If psutil's fix takes longer than our patience allows, or if the problem ends up not actually being with psutil, I'll probably end up taking a closer look.

**Comment by tehsmyers** [comment]
More details in the psutil bug, but they implemented a change to avoid tripping this error and put out a new release. Jenkins builds are working again, and a quick peek at the build currently running on this PR shows that the false positive CPS warnings are no longer appearing with this change. I'll merge it once jenkins is done and green.

**Comment by tehsmyers** [comment]
The Jenkinsfile itself was causing the false positive warning to be emitted, so I updated that. I also updated the README to use the now-correct calling syntax.

While I was in there, I switched the role to test from rhsm (slow) to molecule_openstack_ci (presumably our fastest openstack-based role.

**Pull request merged**
